<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>servo_hardware</name>
  <version>0.0.0</version>
  <description>ROS 2 Control hardware interface for servo control via serial communication</description>
  <maintainer email="glpuga@gmail.com">Gerardo Puga</maintainer>
  <license>BSD</license>
  <author email="glpuga@gmail.com">Gerardo Puga</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>asio</depend>
  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>realtime_tools</depend>
  <depend>asio_cmake_module</depend>
  <depend>servo_protocol_decoder</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
